name: Golden Image Builder
on:
  workflow_dispatch:
  push:
    branches: ["main"] 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      DBUSER: ${{ secrets.DBUSER }}
      DBPASSWORD: ${{ secrets.DBPASSWORD }}
      DBNAME: ${{ secrets.DBNAME }}    
      DBURL: ${{ secrets.DBURL }}

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Start MySQL Services
      run: sudo systemctl start mysql.service 

    - name: Install Dependencies    
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Zip Webapp 
      run: zip -r webapp.zip ./

    - name: Install and Configure gcloud CLI
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        export_default_credentials: true

    - name: Setup Packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "1.10.1"

    - name: Initialize Packer
      run: packer init .

    - name: Format Packer Config
      run: packer fmt -check packer.pkr.hcl

    - name: Validate Packer Config
      run: packer validate packer.pkr.hcl

    - name: Build Image with Packer
      run: packer build packer.pkr.hcl
